/**
 * Jest Configuration
 * 
 * Browser-first web application testing setup:
 * - jsdom environment for Web APIs (AudioContext, localStorage, etc.)
 * - ES modules support via Node.js --experimental-vm-modules
 * - Coverage reporting for critical audio pipeline components
 */

export default {
  // Use jsdom to simulate browser environment
  testEnvironment: 'jsdom',

  // ES modules support
  transform: {
    '\\.proto$': '<rootDir>/jest.text-transformer.cjs', // Transform .proto files as text
  },
  moduleNameMapper: {
    // Mock fs module to avoid graceful-fs import issues
    '^fs$': '<rootDir>/__mocks__/fs.cjs',
    '^node:fs$': '<rootDir>/__mocks__/fs.cjs',
    // Mock Vue for Jest tests (Vue composables tested via integration, not unit tests)
    '^vue$': '<rootDir>/__mocks__/vue.js',
  },

  // Test file patterns
  testMatch: [
    '**/__tests__/**/*.test.js',
  ],

  // Ignore patterns
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/vendors/',
    '/test-results/',
    '/playwright-report/',
    '/tests/playwright/', // Playwright tests use their own runner
  ],

  // Coverage configuration
  collectCoverageFrom: [
    'app/**/*.js',
    '!app/config*.js',
    '!app/theme.js',
    '!app/localize.js',
    '!app/mumble-streams/mumble-proto-minimal.js', // Generated by scripts/generate-proto.sh
    '!app/audio/recorder-worker.js', // AudioWorklet processor - no imports allowed
    '!app/audio/playback-buffer-processor.js', // AudioWorklet processor
    '!app/index.js', // Entry point - hard to test in isolation
    '!app/**/index.js', // Barrel exports - just re-export, no logic to test
  ],

  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json-summary'],

  // Coverage thresholds - 80% minimum enforced
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 80,
      functions: 80,
      lines: 80
    }
  },

  // Setup files
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],

  // Timeouts
  testTimeout: 10000,

  // Show individual test results
  verbose: true,

  // Clear mocks between tests
  clearMocks: true,
  resetMocks: false,
  restoreMocks: false,
};
